'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property ID As Integer
    Public Property productName As String
    Public Property productColor As String
    Public Property productIdentity As String
    Public Property productPrice As Integer
    Public Property productMaterial As String
    Public Property productOriginality As String
    Public Property productCategory As String
    Public Property productGraphics As String

End Class
